services:
  db:
    image: postgres:18.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - db:/data/db
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
volumes:
  db:
    driver:
      local