# default elasticbeanstalk server port
server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  application:
    name: customer_management
  flyway:
    baseline-on-migrate: true